//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.06.29 at 07:47:57 AM JST 
//


package api.v1.model;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the api.v1.model package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _CategoryListDTO_QNAME = new QName("", "CategoryListDTO");
    private final static QName _CustomerListDTO_QNAME = new QName("", "CustomerListDTO");
    private final static QName _VendorListDTO_QNAME = new QName("", "VendorListDTO");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: api.v1.model
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link CategoryListDTO }
     * 
     */
    public CategoryListDTO createCategoryListDTO() {
        return new CategoryListDTO();
    }

    /**
     * Create an instance of {@link CustomerListDTO }
     * 
     */
    public CustomerListDTO createCustomerListDTO() {
        return new CustomerListDTO();
    }

    /**
     * Create an instance of {@link VendorListDTO }
     * 
     */
    public VendorListDTO createVendorListDTO() {
        return new VendorListDTO();
    }

    /**
     * Create an instance of {@link CategoryDTO }
     * 
     */
    public CategoryDTO createCategoryDTO() {
        return new CategoryDTO();
    }

    /**
     * Create an instance of {@link CustomerDTO }
     * 
     */
    public CustomerDTO createCustomerDTO() {
        return new CustomerDTO();
    }

    /**
     * Create an instance of {@link VendorDTO }
     * 
     */
    public VendorDTO createVendorDTO() {
        return new VendorDTO();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CategoryListDTO }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link CategoryListDTO }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "CategoryListDTO")
    public JAXBElement<CategoryListDTO> createCategoryListDTO(CategoryListDTO value) {
        return new JAXBElement<CategoryListDTO>(_CategoryListDTO_QNAME, CategoryListDTO.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CustomerListDTO }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link CustomerListDTO }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "CustomerListDTO")
    public JAXBElement<CustomerListDTO> createCustomerListDTO(CustomerListDTO value) {
        return new JAXBElement<CustomerListDTO>(_CustomerListDTO_QNAME, CustomerListDTO.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link VendorListDTO }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link VendorListDTO }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "VendorListDTO")
    public JAXBElement<VendorListDTO> createVendorListDTO(VendorListDTO value) {
        return new JAXBElement<VendorListDTO>(_VendorListDTO_QNAME, VendorListDTO.class, null, value);
    }

}
